channels:
  - conda-forge

dependencies:
  - python=3.12.1              # https://pyreadiness.org/3.9/
  - beautifulsoup4=4.12.2      # https://www.crummy.com/software/BeautifulSoup/
  - pip=23.3.2                 # https://pip.pypa.io/en/stable/news/
  - pip:
      - robocorp==1.2.4
      - robocorp-browser==2.2.1
